import { mapValues } from 'lodash'

export default (schema) => mapValues({
  REQUEST_COLLECTION:        'REQUEST_COLLECTION',
  UPDATE_COLLECTION:         'UPDATE_COLLECTION',

  REQUEST_SEARCH:            'REQUEST_SEARCH',
  UPDATE_SEARCH_DATA:        'UPDATE_SEARCH_DATA',

  UPDATE_PAGE:               'UPDATE_PAGE',

  UPDATE_FILTERS:            'UPDATE_FILTERS',
  UPDATE_FILTER_FIELDS:      'UPDATE_FILTER_FIELDS',
  UPDATE_FILTER_FUNCTIONS:   'UPDATE_FILTER_FUNCTIONS',
  UPDATE_SEARCH:             'UPDATE_SEARCH',

  REQUEST_RESOURCE:          'REQUEST_RESOURCE',
  UPDATE_RESOURCE:           'UPDATE_RESOURCE',

  PREPARING_RESOURCE:        'PREPARING_RESOURCE',

  UPDATE_NEW_RESOURCE:       'UPDATE_NEW_RESOURCE',
  CREATING_RESOURCE:         'CREATING_RESOURCE',
  RESET_NEW_RESOURCE:        'RESET_NEW_RESOURCE',
  DELETE_RESOURCE:           'DELETE_RESOURCE',

  UPDATE_EDIT_RESOURCE:      'UPDATE_EDIT_RESOURCE',
  PATCHING_RESOURCE:         'PATCHING_RESOURCE',
  RESET_EDIT_RESOURCE:       'RESET_EDIT_RESOURCE',

  UPDATE_DUPLICATE_RESOURCE: 'UPDATE_DUPLICATE_RESOURCE',
  DUPLICATING_RESOURCE:      'DUPLICATING_RESOURCE',
  RESET_DUPLICATE_RESOURCE:  'RESET_DUPLICATE_RESOURCE',

  SET_ERROR:                 'SET_ERROR'
}, constant => (schema.key + '/' + constant))
